Repository WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-2-Team-B, pull requests merged in 2024-12, with the labels that each got.

#52 configuration des tests et workflows github
  .github/workflows/lint.yml
  api/auth/Dockerfile
  api/auth/jest.config.ts
  api/auth/package-lock.json
  api/auth/package.json
  api/auth/tests/jest.setup.ts
  api/email/Dockerfile
  api/email/jest.config.ts
  api/email/package-lock.json
  api/email/package.json
  api/email/tests/jest.setup.ts
  api/product/dockerfile
  api/product/jest.config.ts
  api/product/package.json
  api/product/tests/jest.setup.ts
  api/uploadimage/Dockerfile
  api/uploadimage/jest.config.ts
  api/uploadimage/package-lock.json
  api/uploadimage/package.json
  api/uploadimage/tests/jest.setup.ts
  client/Dockerfile
  client/package.json
  docker-compose.test.yml
  docker-compose.yml
  package-lock.json
  package.json
Labels: REVIEW REQUESTED

#62 US08/api create a newProduct
  api/product/src/entity/product.entities.ts
  api/product/src/resolvers/product.resolvers.ts
Labels: REVIEW REQUESTED

#64 Us8 front
  client/package-lock.json
  client/package.json
  client/src/main.tsx
  client/src/pages/Catalog.ts
  client/src/pages/Catalog.tsx
  client/vite.config.ts
  docker-compose.yml
  nginx.conf
Labels: REVIEW REQUESTED

#70 Feature/category management
  api/product/src/data-source.ts
  api/product/src/entity/category.entities.ts
  api/product/src/resolvers/category.resolver.ts
  api/product/src/schema.ts
  client/src/components/CategoryForm.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/ManagementProduct.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#73 Feature/update category
  api/product/src/entity/category.entities.ts
  api/product/src/resolvers/category.resolver.ts
  client/src/components/CategoryForm.tsx
  client/src/components/CharacteristicForm.tsx
  client/src/generated/graphql-types.ts
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#74 Feature/update product
  api/product/src/__test__/product.test.ts
  api/product/src/__test__/schemas/mutations.ts
  api/product/src/__test__/schemas/queries.ts
  api/product/src/entity/product.entities.ts
  api/product/src/resolvers/product.resolvers.ts
  api/product/src/types/product.types.ts
  client/src/components/CardProduct.tsx
  client/src/components/ProductDetails.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/Catalog.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#75 Fixcreatproduct
  .gitignore
  api/auth/src/index.ts
  api/product/src/data-source.ts
  api/product/src/entity/characteristic.entities.ts
  api/product/src/entity/image.entities.ts
  api/product/src/resolvers/image.resolvers.ts
  api/product/src/schema.ts
  api/uploadimage/package-lock.json
  api/uploadimage/package.json
  api/uploadimage/src/index.ts
  api/uploadimage/uploads/1733394454116-chiara.jpg
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/Addimage.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
  makefile
Labels: REVIEW REQUESTED

#77 Feature/category soft delete
  api/product/src/entity/category.entities.ts
  api/product/src/resolvers/category.resolver.ts
  client/codegen.ts
  client/src/components/CategoryForm.tsx
  client/src/generated/graphql-types.ts
  client/src/schema/mutations.ts
Labels: REVIEW REQUESTED

#79 add a search bar and add creationpage in the front
  api/product/src/resolvers/product.resolvers.ts
  client/package-lock.json
  client/package.json
  client/src/components/CreationProduct.tsx
  client/src/components/NavBar.tsx
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/AddProduct.tsx
  client/src/pages/Catalog.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED, REVIEWED

#80 Feat/tag form
  api/product/src/resolvers/tag.resolver.ts
  client/src/components/TagForm.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/ManagementProduct.tsx
  client/src/schema/mutations.ts
Labels: REVIEW REQUESTED

#81 feature/ display tag
  client/src/components/TagForm.tsx
  client/src/components/TagItem.tsx
  client/src/generated/graphql-types.ts
  client/src/schema/queries.ts
Labels: REVIEWED

#82 Feature/update product
  client/src/components/ProductDetails.tsx
Labels: REVIEW REQUESTED

#83 Feature/tag edition
  api/product/src/resolvers/tag.resolver.ts
  client/src/components/TagForm.tsx
  client/src/components/TagItem.tsx
  client/src/generated/graphql-types.ts
  client/src/schema/mutations.ts
Labels: REVIEW REQUESTED

#85 Implement tag soft delete functionality
  api/product/src/entity/tag.entities.ts
  api/product/src/resolvers/tag.resolver.ts
  api/product/src/types/tag.types.ts
  client/src/components/TagForm.tsx
  client/src/components/TagItem.tsx
  client/src/generated/graphql-types.ts
  client/src/schema/mutations.ts
Labels: REVIEW REQUESTED

#84 Updateproductpage
  api/product/src/entity/image.entities.ts
  api/product/src/resolvers/image.resolvers.ts
  api/uploadimage/src/config.ts
  api/uploadimage/src/index.ts
  api/uploadimage/src/middlewares/cors.ts
  api/uploadimage/src/middlewares/multer.ts
  api/uploadimage/src/routes/upload.routes.ts
  api/uploadimage/src/services/upload.ts
  api/uploadimage/uploads/1733845841977-ipad_1.jpg
  api/uploadimage/uploads/1733846897353-ssd_1.jpg
  api/uploadimage/uploads/1733847127700-iphone_2 (1).jpg
  api/uploadimage/uploads/1733847260490-iphone_1.jpg
  api/uploadimage/uploads/1733847545569-iphone_1.jpg
  api/uploadimage/uploads/1733847832134-iphone_3.jpg
  api/uploadimage/uploads/1733848090167-printer_4.jpg
  api/uploadimage/uploads/1733848617889-dellpc_2.jpg
  api/uploadimage/uploads/1733909427723-dellpc_3.jpg
  api/uploadimage/uploads/1733913538025-ssd_2.jpg
  api/uploadimage/uploads/1733927640943-ipad_3.jpg
  api/uploadimage/uploads/1733927809649-ipad_3.jpg
  api/uploadimage/uploads/1733928095389-ssd_2.jpg
  api/uploadimage/uploads/1733930300079-ssd_3.jpg
  api/uploadimage/uploads/1733930507614-hard_disk_2.jpg
  api/uploadimage/uploads/1733931652120-macbook_2.jpg
  api/uploadimage/uploads/1733933929828-samsung_mobile_3.jpg
  client/package-lock.json
  client/package.json
  client/src/components/AddImage.tsx
  client/src/components/CreationProduct.tsx
  client/src/main.tsx
  client/src/pages/AddProduct.tsx
  client/src/pages/Addimage.tsx
  client/src/pages/Catalog.tsx
  client/src/schema/mutations.ts
Labels: REVIEW REQUESTED

#86 Brand creation
  api/product/jest.config.ts
  api/product/package.json
  api/product/src/__test__/brand.test.ts
  api/product/src/__test__/helpers/generateRandomString.helper.ts
  api/product/src/__test__/helpers/test.helpers.ts
  api/product/src/__test__/schemas/mutations.ts
  api/product/src/data-source.ts
  api/product/src/entity/brand.entities.ts
  api/product/src/resolvers/brand.resolvers.ts
  api/product/src/schema.ts
  api/product/src/types/brand.types.ts
  api/uploadimage/src/index.ts
  api/uploadimage/tsconfig.json
  client/package-lock.json
  client/package.json
  client/src/__test__/AddBrand.test.tsx
  client/src/components/AddBrand.tsx
  client/src/components/AddImage.tsx
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/BrandManagement.tsx
  client/src/schema/mutations.ts
  client/tests/setupTest.ts
Labels: REVIEW REQUESTED

#88 Feature/product category association
  api/product/src/entity/category.entities.ts
  api/product/src/entity/product.entities.ts
  api/product/src/resolvers/product.resolvers.ts
  api/product/src/types/product.types.ts
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/ProductDetails.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#89 Feature/view brand
  api/product/src/__test__/brand.test.ts
  api/product/src/__test__/helpers/test.helpers.ts
  api/product/src/__test__/schemas/queries.ts
  api/product/src/resolvers/brand.resolvers.ts
  client/src/__test__/AddBrand.test.tsx
  client/src/components/AddBrand.tsx
  client/src/components/BrandCard.tsx
  client/src/components/BrandCatalog.tsx
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/BrandManagement.tsx
  client/src/pages/Catalog.tsx
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#90 Add category selection to product creation form
  client/src/components/CreationProduct.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/ProductDetails.tsx
  client/src/schema/mutations.ts
Labels: REVIEW REQUESTED

#96 Feature/associate a brand to a product
  api/product/src/__test__/brand.test.ts
  api/product/src/__test__/product.test.ts
  api/product/src/__test__/schemas/mutations.ts
  api/product/src/__test__/schemas/queries.ts
  api/product/src/entity/brand.entities.ts
  api/product/src/entity/product.entities.ts
  api/product/src/resolvers/brand.resolvers.ts
  api/product/src/resolvers/product.resolvers.ts
  api/product/src/types/product.types.ts
  client/src/components/CreationProduct.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/ProductDetails.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#97 Feature/product status
  api/product/src/entity/product.entities.ts
  api/product/src/resolvers/product.resolvers.ts
  api/product/src/types/product.types.ts
  client/src/components/CreationProduct.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/ProductDetails.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEW REQUESTED

#100 Feature/deactivate brand
  api/product/src/__test__/brand.test.ts
  api/product/src/__test__/schemas/mutations.ts
  api/product/src/__test__/schemas/queries.ts
  api/product/src/entity/brand.entities.ts
  api/product/src/resolvers/brand.resolvers.ts
  api/product/src/types/brand.types.ts
  client/codegen.ts
  client/src/components/BrandCard.tsx
  client/src/components/BrandCatalog.tsx
  client/src/components/BrandDetails.tsx
  client/src/generated/graphql-types.ts
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
  client/src/ui/Switch.tsx
Labels: REVIEW REQUESTED
